# Generated by Django 4.2.9 on 2024-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitallearningresource',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=450, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='digitallearningresource',
            name='slug',
            field=models.SlugField(max_length=450, unique=True),
        ),
        migrations.AlterField(
            model_name='digitallearningresource',
            name='url',
            field=models.URLField(blank=True, max_length=450, null=True, unique=True),
        ),
    ]
