# Generated by Django 4.2.9 on 2024-10-13 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('platformCreatorId', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platformThumbnailUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('thumbnailUrl', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('isoCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platformCourseId', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('isFree', models.BooleanField(default=True)),
                ('dollarPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hasCertificate', models.BooleanField(default=False)),
                ('certificateDollarPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platformLastMod', models.DateTimeField(blank=True, null=True)),
                ('platformThumbnailUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('thumbnailUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('reviewsCount', models.PositiveIntegerField(default=0)),
                ('reviewsRating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('creators', models.ManyToManyField(to='core.creator')),
                ('formats', models.ManyToManyField(to='core.format')),
                ('languages', models.ManyToManyField(to='core.language')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isScraping', models.BooleanField(default=False)),
                ('lastFullScrape', models.DateTimeField(blank=True, null=True)),
                ('isIndependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(help_text='1 is the highest level, 2 is sub-category')),
                ('parentTag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='digitallearningresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='digitallearningresource',
            name='platform',
        ),
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
        migrations.DeleteModel(
            name='DigitalLearningResource',
        ),
        migrations.DeleteModel(
            name='DigitalLearningResourceCategory',
        ),
        migrations.DeleteModel(
            name='DigitalLearningResourcePlatform',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.level'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='platformId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.platform'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
        migrations.AddField(
            model_name='creator',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.creatortype'),
        ),
    ]
