# Generated by Django 4.2.9 on 2024-10-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creator_creatortype_format_language_learningresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='isLimitedFree',
            field=models.BooleanField(default=False),
        ),
    ]
