# Generated by Django 4.2.9 on 2024-11-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_platformcreatorid_creator_platform_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='type',
        ),
        migrations.DeleteModel(
            name='CreatorType',
        ),
    ]
