# Generated by Django 4.2.9 on 2024-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_creator_type_delete_creatortype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='duration',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='duration_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
