# Generated by Django 4.2.9 on 2024-11-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_learningresource_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='formats',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.format'),
        ),
    ]
