# Generated by Django 4.2.9 on 2024-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_learningresource_formats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
