# Generated by Django 4.2.9 on 2024-11-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_platform_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='platform_id',
            new_name='platform_creator_id',
        ),
        migrations.AddField(
            model_name='creator',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.platform'),
        ),
    ]
