# Generated by Django 4.2.9 on 2024-11-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_platform_id_creator_platform_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
