x-app: &default-app
  image: ghcr.io/swottinglabs/swotting-prod:latest
  restart: unless-stopped
  env_file: .env
  logging:
    driver: journald
    options:
      mode: non-blocking

services:
  web:
    <<: *default-app
    environment:
        - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
        - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
    ports:
      - "127.0.0.1:8006:8000"
    command: gunicorn -b 0.0.0.0:8000 --timeout 120 --capture-output swotting.wsgi

  swottingdb:
    container_name: swottingdb
    image: ankane/pgvector:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5432:5432"
    environment: # set the environment variables here
      POSTGRES_USER: swotting
      POSTGRES_PASSWORD: swotting
      POSTGRES_DB: swotting
    env_file:
      - ./.env


volumes:
  postgres_data: