x-app: &default-app
  image: ghcr.io/swottinglabs/swotting-prod:latest
  restart: unless-stopped
  env_file: .env
  logging:
    driver: journald
    options:
      mode: non-blocking
  depends_on:
    - redis
    - swottingdb

services:
  web:
    <<: *default-app
    environment:
        - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
        - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
    ports:
      - "127.0.0.1:8006:8000"
    command: gunicorn -b 0.0.0.0:8000 --timeout 120 --capture-output swotting.wsgi

  celery_worker:
    <<: *default-app
    command: celery -A swotting worker --loglevel=info
    environment:
      - C_FORCE_ROOT=true
    deploy:
      replicas: 2

  celery_beat:
    <<: *default-app
    command: celery -A swotting beat --loglevel=info
    deploy:
      replicas: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  swottingdb:
    container_name: swottingdb
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: swotting
      POSTGRES_PASSWORD: swotting
      POSTGRES_DB: swotting
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: