# Generated by Django 4.2.11 on 2025-01-15 03:48

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('time_started', models.DateTimeField(db_index=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('items_scraped', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('module', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('settings', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Scrapy settings object for this spider only.')),
                ('log_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info'), ('DEBUG', 'Debug'), ('NOTSET', 'Not Set')], default='INFO', max_length=20)),
                ('faulty', models.BooleanField(db_index=True, default=False)),
                ('crawlera_spider', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('execution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.execution')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.spider')),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.spider'),
        ),
    ]
