name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --cache-dir .cache/pip -U pip
          pip install --cache-dir .cache/pip -e .
      - name: Collect static
        run: python manage.py collectstatic --noinput
      - name: Run tests
        run: python manage.py test
        env:
          HUEY_IMMEDIATE: 'True'
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

  build-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/django/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-image-name:latest
